


#include "random.H"

namespace Foam
{
/*
 * @name    randomDistHandler
 * @info    The function handles the distribution function called by user
 * 
 * @input   distributionFunctionName    name of distribution function
 *          randomNumber                random number generated by given PDF
 *          mean                        mean value of randomNumber (define in inject.dat file)
 *          variance_                   variance of distribution function
 *          numObject                   number of random number
 * 
 * @output randomNumber                 generated random umber
 * 
 * @author  Mehdi Baba Mehdi
 */
void randomDistHandler(std::string distributionFunctionName, scalar* randomNumber, const scalar& mean, const scalar& variance_, const int& numObject)
{
    void (*distFunction)(scalar*, const scalar&, const scalar&, const int&);
    if(distributionFunctionName == "guassian")
    {
            distFunction = guassianDistribution;
    } else if (distributionFunctionName == "exponential")
    {
        distFunction = exponentialDistribution;

    } else
    {
        std::cerr << "No available distribution function specified" << std::endl;
    }
    distFunction(randomNumber, mean, variance_, numObject);
}

/*
 * @name    guassianDistribution
 * @info    The function generates random numbers according to guassian distribution 
 *        
 * @input   randomNumber                random number generated by given PDF
 *          mean                        mean value of randomNumber (define in inject.dat file)
 *          variance_                   variance of distribution function
 *          numObject                   number of random number
 * 
 * @output randomNumber                 generated random umber
 * 
 * @author  Mehdi Baba Mehdi
 */

void guassianDistribution(scalar* randomNumber, const scalar& mean, const scalar& variance_, const int& numObject)
{
  std::default_random_engine generator;
  std::normal_distribution<scalar> distribution(mean,variance_);

  for (int i = 0; i < numObject; ++i) 
  {
    *(randomNumber++) = distribution(generator);
  }
}
     
     
/*
 * @name    exponentialDistribution
 * @info    The function generates random numbers according to exponential distribution
 *          
 * @input   randomNumber                random number generated by given PDF
 *          mean                        mean value of randomNumber (define in inject.dat file)
 *          variance_                   variance of distribution function
 *          numObject                   number of random number
 * 
 * @output randomNumber                 generated random umber
 * 
 * @author  Mehdi Baba Mehdi
 */

void exponentialDistribution(scalar* randomNumber, const scalar& mean, const scalar& variance_, const int& numObject)
{
  std::default_random_engine generator;
  std::exponential_distribution<scalar> distribution(mean);

  for (int i = 0; i < numObject; ++i) 
  {
    *(randomNumber++) = distribution(generator);
  } 
}     

} 
